# Generated by Django 4.2.20 on 2025-04-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalAttachment',
        ),
    ]
